### ISSUE TITLE
Support for yarn

### ISSUE THREAD

**Issue by loeklj** [davidchambers/xyz#38]
I'm new to opening issues and collaboration to XYZ, so let me know if there are policies on how to address issues and help out.

When using yarn to call XYZ to release to npm registry the underlying npm call gives an `ENEEDAUTH` error and fails with exit code 1:

```
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```
That is, support for yarn that uses `yarn publish`?

**Comment by Avaq** [comment]
You can use [`--publish-command`](https://github.com/davidchambers/xyz/blob/master/xyz#L34-L36) to set the command used by XYZ to do the publishing.

**Comment by davidchambers** [comment]
Hello, @loeklj. I'm pleased to see that you discovered xyz. :)

It sounds to me as though there are two issues here. One is that you'd like to use `yarn publish` rather than `npm publish`. This is possible with __`--publish-command`__, as @Avaq mentioned.

The second issue is that I assume you'll need to run `npm adduser` (or whichever `yarn` command wraps it) in order to be allowed to publish to the npm registry. If you ran `xyz` and it successfully pushed to GitHub or wherever your project is hosted, but then failed to publish to the npm registry, the fix is to run `npm adduser` then run `npm publish` (or `yarn publish`) manually. Your __~/.npmrc__ will then contain an auth token so it won't be necessary to run `npm adduser` again in future.
