### ISSUE TITLE
xyz 3.0.0 doesn't work on macOS

### ISSUE THREAD

**Issue by be9** [davidchambers/xyz#51]
Hey David, looks like your associative array refactoring in 141d5adde026a2d7185db9b0d0ce87c49e854589 broke things in macOS as it ships with 
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
```
and associative arrays only appeared in Bash 4.x:

```
$ node_modules/.bin/xyz
node_modules/.bin/xyz: line 125: branch: unbound variable
```

**Comment by davidchambers** [comment]
Good point, @be9. I may not have made this change had I realized at the time that it relies on a “new” (nine-year-old) Bash feature. I'm reluctant to revert the change: xyz is dependable not because it has an extensive test suite—it does not—but because it is modified infrequently and carefully.

I suggest you either run `brew install bash` or stick with `xyz@2.1.0`. If for some reason neither of these suggestions is suitable, please share your requirements so we can discuss other solutions.

**Comment by be9** [comment]
I think we can stay at 2.1.0 at Plaid. However you'd want to note the fact that Bash 4+ is required in the README.
